on:
  workflow_dispatch:

  
jobs:
  build_workflow:
    uses: ./.github/workflows/build.yml
    with:
      NODE_VERSION: '14.x'
  deploy_dev:
    needs: [build_workflow]
    uses: ./.github/workflows/deploy.yml
    with:
      AZURE_WEBAPP_NAME: 'AzureAngualrWebApp'
      AZURE_WEBAPP_PACKAGE_PATH: '.' 
      ENVIRONMENT: 'development'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  deploy_qa:
    needs: [deploy_dev]
    uses: ./.github/workflows/deploy.yml
    with:
      AZURE_WEBAPP_NAME: 'AzureAngualrWebApp-QA'
      AZURE_WEBAPP_PACKAGE_PATH: '.' 
      ENVIRONMENT: 'qa'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        